=== beadeval/Actividad2/Actividad2/A2Requerimiento2.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
    <!-- El nodo raíz se llama "biblioteca"-->
    <element name="biblioteca">
      <complexType>
       <sequence>
            <element name="libros">
               <complexType>
                  <sequence>
                     <element name="libro" maxOccurs="unbounded">
                    
                        <!-- Elementos de libro -->
                           <complexType>
                              <sequence>
                                 <element name="titulo" type="string"/>
                                 <element name="capitulo" maxOccurs="unbounded">
                                     <complexType>
                                      <sequence>
                                           <element name="nombre_capitulo" type="string"/>
                                           <element name="contenido" maxOccurs="unbounded" >
                                              <complexType>
                                               <attribute name="enlace" type="string" use="required"></attribute>
                                              </complexType>
                                            </element>
                                      </sequence>
                                     </complexType>
                                 </element>
                                 <element name="indice_libro" type="string"/>
                                 <element name="sinopsis" type="string"/>
                             </sequence>      
                          
                   <!-- Atributos de libro -->
                           
                                <attribute name="id" use="required">
                                 <simpleType>
                                   <restriction base="string">
                                      <enumeration value="L0001"></enumeration>
                                      <enumeration value="L0002"></enumeration>
                                      <enumeration value="L0003"></enumeration>
                                   </restriction>
                                 </simpleType>
                                </attribute>
                                <attribute name="tipo_clase" use="required">
                                  <simpleType>
                                   <restriction base="string">
                                      <enumeration value="novela"></enumeration>
                                      <enumeration value="infantil"></enumeration>
                                      <enumeration value="didáctico"></enumeration>
                                   </restriction>
                                  </simpleType>
                                </attribute>
                                <attribute name="numero_paginas" use="required"></attribute>
                           </complexType>
                     </element> 
                  </sequence>
          
               
                 <!-- Atributos de libros -->
                        <attribute name="id" type="string" use="required" fixed="L" />
                </complexType> 
               </element>    
            
            
            <element name="revistas">
                <complexType>
                  <sequence>
                        <element name="revista" maxOccurs="unbounded">
                    
                   <!-- Elementos de revistas -->
                            <complexType>
                              <sequence>
                                 <element name="titulo_revista" type="string"/>
                                 <element name="numero_revista" type="integer" />
                                 <element name="indice_revista" type="string" />
                                 <element name="secciones_revista" maxOccurs="unbounded">
                                     <complexType>
                                         <sequence>
                                           <element name="contenido_revista" maxOccurs="unbounded">
                                             <complexType> 
                                                <attribute name="enlace_revista" type="string" use="required"/> 
                                             </complexType>
                                           </element>
                                         </sequence>
                                     <attribute name="numero_paginas" type="integer" use="required"/>
                                    </complexType>
                                 </element>
                              </sequence>
                       
                 
                   <!-- Atributos de revista -->
                                <attribute name="id" use="required">
                                 <simpleType>
                                   <restriction base="string">
                                      <enumeration value="R0001"></enumeration>
                                      <enumeration value="R0002"></enumeration>
                                      <enumeration value="R0003"></enumeration>
                                      <enumeration value="R0004"></enumeration>
                                      <enumeration value="R0005"></enumeration>
                                   </restriction>
                                  </simpleType>
                                </attribute>
                                <attribute name="tipo_clase" use="required">
                                  <simpleType>
                                   <restriction base="string">
                                      <enumeration value="informática"></enumeration>
                                      <enumeration value="corazón"></enumeration>
                                      <enumeration value="coches"></enumeration>
                                      <enumeration value="investigación"></enumeration>
                                      <enumeration value="otras"></enumeration>
                                   </restriction>
                                  </simpleType>
                                </attribute>
                                <attribute name="numero_paginas" use="required"/>
                           </complexType>
                       </element>
                     </sequence>
                       <!-- Atributos de revistas -->
                        <attribute name="id" type="string" use="required" fixed="R" />
                </complexType>
            </element>

            <element name="periodicos">
                  <complexType>
                     <sequence>
                        <element name="periodico" maxOccurs="unbounded">
                  
                   <!-- Elementos de periodico -->
                            <complexType>
                              <sequence>
                                 <element name="titulo_periodico" type="string"/>
                                 <element name="indice_contenido" type="string" />
                                 <element name="secciones_periodico" maxOccurs="unbounded">
                                    <complexType>
                                       <sequence>
                                           <element name="seccion">
                                             <complexType>
                                              <sequence>
                                               <element name="articulos">
                                                 <complexType>
                                                   <attribute name="autor" type="string" use="required"/>
                                          
                                                 <complexType>
                                                  <sequence>
                                                      <element name="contenido articulos">
                                                        <complexType>
                                                           <attribute name="enlace_periodico" type="string" use="required"/>
                                                        </complexType>
                                                      </element>
                                                   </sequence>
                                                  </complexType>
                                               </complexType>
                                               </element>
                                              </sequence>
                                             </complexType>
                                             </element>
                                           <attribute name="id" type="string" use="required"> 
                                              <simpleType>
                                                 <restriction base="string">
                                                    <enumeration value="economica"></enumeration>
                                                    <enumeration value="autor"></enumeration>
                                                    <enumeration value="deportes"></enumeration>
                                                    <enumeration value="nacional"></enumeration>
                                                    <enumeration value="internacional"></enumeration>
                                                 </restriction>
                                              </simpleType>
                                            </attribute>
                                            </sequence>
                                    </complexType>
                                  </element>
                                          
                              </sequence>  
                                  <attribute name="numero_paginas" type="integer" use="required"/>
                            </complexType>
                        </element>
                               <complexType>      
                   <!-- Atributos de periodico -->
                                <attribute name="id" use="required">
                                 <simpleType>
                                   <restriction base="string">
                                      <enumeration value="P0001"></enumeration>
                                      <enumeration value="P0002"></enumeration>
                                   </restriction>
                                  </simpleType>
                                </attribute>
                                <attribute name="tipo_clase" use="required">
                                  <simpleType>
                                   <restriction base="string">
                                      <enumeration value="nacionales"></enumeration>
                                      <enumeration value="internacionales"></enumeration>
                                   </restriction>
                                  </simpleType>
                                </attribute>
                                <attribute name="fecha_publicacion" use="required"></attribute>
                     </sequence>
                       
                        <!-- Atributos de periodicos -->
                        <attribute name="id" type="string" use="required" fixed="P" />
                  </complexType>
             </element>
         </sequence>
      </complexType>
  </element>
</schema>

=== beadeval/Actividad2/Actividad2/A2Requerimiento2.xml
<?xml version="1.0" encoding="UTF-8"?>
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:noNamespaceSchemaLocation= "A2Requerimiento2.xsd">
    <!--Libros-->
  <libros id="L">
    <!--Atributos de libros tipo novela-->
   <libro id="L0001" tipo_clase="novela" numero_paginas="Numero paginas">
          <titulo>Titulo de Novela </titulo>
          <capitulo numero_paginas="Numero paginas">
               <nombre_capitulo>Nombre del capitulo</nombre_capitulo>
               <contenido enlace="https://www.actividad2.com"/>
          </capitulo>
          <indice_libro>Contenido del indice</indice_libro>
          <sinopsis>Contenido de la sinopsis</sinopsis>
    </libro>
   <!--Atributos de libros tipo infantil-->
    <libro id="L0002" tipo_clase="infantil" numero_paginas="Numero paginas">
          <titulo>Titulo de Libro Infantil</titulo>
          <capitulo numero_paginas="Numero paginas">
               <nombre_capitulo>Nombre del capitulo</nombre_capitulo>
               <contenido enlace="https://www.actividad2.com"/>
          </capitulo>
          <indice_libro>Contenido del indice</indice_libro>
          <sinopsis>Contenido de la sinopsis</sinopsis>
  </libro>
    <!--Atributos de libros tipo didáctico-->
    <libro id="L0003" tipo_clase="didáctico" numero_paginas="Numero paginas">
          <titulo>Titulo de Libro Didáctico</titulo>
          <capitulo numero_paginas="Numero paginas">
               <nombre_capitulo>Nombre del capitulo</nombre_capitulo>
               <contenido enlace="https://www.actividad2.com"/>
          </capitulo>
          <indice_libro>Contenido del indice</indice_libro>
          <sinopsis>Contenido de la sinopsis</sinopsis>
    </libro>
    </libros>
    <!--Revistas-->
  <revistas id="R">
    <!--Atributos de revistas tipo informática-->
    <revista id="R0001" tipo_clase="informática" numero_paginas="Numero de Páginas">
          <titulo_revista>Titulo Revista Informática</titulo_revista>
          <numero_revista>1</numero_revista>
          <indice_revista>Contenido del índice</indice_revista>
          <secciones_revista numero_paginas= "10">
               <contenido_revista enlace_revista="https://www.actividad2.com"/>
          </secciones_revista>
    </revista>
    <!--Atributos de revistas tipo corazón-->
    <revista id="R0002" tipo_clase="corazón" numero_paginas="Numero de Páginas">
          <titulo_revista>Titulo Revista Corazón</titulo_revista>
          <numero_revista>2</numero_revista>
          <indice_revista>Contenido del índice</indice_revista>
          <secciones_revista numero_paginas="20">
               <contenido_revista enlace_revista="https://www.actividad2.com"/>
          </secciones_revista>
    </revista>
    <!--Atributos de revistas tipo coches-->
    <revista id="R0003" tipo_clase="coches" numero_paginas="Numero de Páginas">
          <titulo_revista>Titulo Revista Coches</titulo_revista>
          <numero_revista>3</numero_revista>
          <indice_revista>Contenido del índice</indice_revista>
          <secciones_revista numero_paginas="30">
               <contenido_revista enlace_revista="https://www.actividad2.com"/>
          </secciones_revista>
    </revista>
    <!--Atributos de revistas tipo investigación-->
    <revista id="R0004" tipo_clase="investigación" numero_paginas="Numero de Páginas">
          <titulo_revista>Titulo Revista Investigación</titulo_revista>
          <numero_revista>4</numero_revista>
          <indice_revista>Contenido del índice</indice_revista>
          <secciones_revista numero_paginas="40">
               <contenido_revista enlace_revista="https://www.actividad2.com"/>
          </secciones_revista>
    </revista>
    <!--Atributos de revistas tipo otras-->
    <revista id="R0005" tipo_clase="otras" numero_paginas="Numero de Páginas">
          <titulo_revista>Titulo Revista Otras</titulo_revista>
          <numero_revista>5</numero_revista>
          <indice_revista>Contenido del índice</indice_revista>
          <secciones_revista numero_paginas="50">
               <contenido_revista enlace_revista="https://www.actividad2.com"/>
          </secciones_revista>
    </revista>
  </revistas>
    
    <!--Periódicos-->
  <periodicos id="P">
    <!--Atributos de periódicos tipo nacional-->
    <periodico id="P0001" tipo_clase="nacionales" fecha_publicacion="Fecha publicacion">
          <titulo_periodico>Titulo del periódico</titulo_periodico>
          <indice_contenido>Indice contenido</indice_contenido>
          <secciones_periodico>
            <seccion id="economica">
              <articulos autor="Autor">
                <contenido_articulos enlace_periodico="https://www.actividad2.com"/>
              </articulos>
          </seccion>

           <seccion id="opinion">
              <articulos autor="Autor">
                <contenido_articulos enlace_periodico="https://www.actividad2.com"/>
              </articulos>
           </seccion>

           <seccion id="deportes">
              <articulos autor="Autor">
                <contenido_articulos enlace_periodico="https://www.actividad2.com"/>
              </articulos>
           </seccion>

           <seccion id="nacional">
              <articulos autor="Autor">
                <contenido_articulos enlace_periodico="https://www.actividad2.com"/>
              </articulos>
           </seccion>

           <seccion id="internacional">
              <articulos autor="Autor">
                <contenido_articulos enlace_periodico="https://www.actividad2.com"/>
              </articulos>
           </seccion>
          </secciones_periodico>
    </periodico>

    <!--Atributos de periódicos tipo internacional-->
    <periodico id="P0002" tipo_clase="internacionales" fecha_publicacion="Fecha publicacion">
          <titulo_periodico>Titulo del periódico</titulo_periodico>
          <indice_contenido>Indice contenido</indice_contenido>
          <secciones_periodico>
            <seccion id="economica">
              <articulos autor="Autor">
                <contenido_articulos enlace_periodico="https://www.actividad2.com"/>
              </articulos>
          </seccion>

           <seccion id="opinion">
              <articulos autor="Autor">
                <contenido_articulos enlace_periodico="https://www.actividad2.com"/>
              </articulos>
           </seccion>

           <seccion id="deportes">
              <articulos autor="Autor">
                <contenido_articulos enlace_periodico="https://www.actividad2.com"/>
              </articulos>
           </seccion>

           <seccion id="nacional">
              <articulos autor="Autor">
                <contenido_articulos enlace_periodico="https://www.actividad2.com"/>
              </articulos>
           </seccion>

           <seccion id="internacional">
              <articulos autor="Autor">
                <contenido_articulos enlace_periodico="https://www.actividad2.com"/>
              </articulos>
           </seccion>
          </secciones_periodico>
    </periodico>
  </periodicos>
     


</biblioteca>
