=== beadeval/Actividad2/Actividad2/A2Requerimiento1.dtd
<!-- Definición de elementos/atributos de bibilioteca -->
<!ELEMENT biblioteca (libros, revistas, periodicos)>
   

<!-- Definición de los atributos de libros -->
    <!ATTLIST libros id ID #REQUIRED>  
    <!ELEMENT libros (libro+)>
    
<!-- Definición de los atributos de libro-->

    <!ATTLIST libro id ID #REQUIRED>
    <!ATTLIST libro tipo_clase (novela | infantil | didactico) #REQUIRED>
    <!ATTLIST libro numero_paginas CDATA #REQUIRED>

<!ELEMENT libro (titulo,capitulo,indice_libro,sinopsis)>
    <!ELEMENT titulo (#PCDATA)>
   
    <!ELEMENT indice_libro (#PCDATA)>
    <!ELEMENT sinopsis (#PCDATA)>

<!ELEMENT capitulo (nombre_capitulo,contenido)>
    <!ELEMENT nombre_capitulo (#PCDATA)>    
    <!ELEMENT contenido (enlace*)>
    
<!-- Definición de los atributos de capitulo -->
    <!ATTLIST capitulo numero_paginas CDATA #REQUIRED>

   <!ATTLIST contenido enlace CDATA #REQUIRED>
      
<!-- Definición de los atributos de revistas-->
    <!ATTLIST revistas id ID #REQUIRED>
    <!ELEMENT revistas (revista+)>
    
<!-- Definición de los atributos de revista -->
    <!ATTLIST revista id ID #REQUIRED>
    <!ATTLIST revista tipo_clase (informatica | corazon | coches| investigacion | otras ) #REQUIRED>
    <!ATTLIST revista numero_paginas CDATA #REQUIRED>

<!ELEMENT revista (titulo_revista,numero_revista,indice_revista,secciones_revista)>
    <!ELEMENT titulo_revista (#PCDATA)>
    <!ELEMENT numero_revista (#PCDATA)>
    <!ELEMENT indice_revista (#PCDATA)>
    <!ELEMENT secciones_revista (contenido_revista)>
    <!ELEMENT contenido_revista (enlace_revista*)>

<!-- Definición de los atributos de secciones_revista -->
    <!ATTLIST secciones_revista numero_paginas CDATA #REQUIRED>

<!-- Definición de los atributos de contenido_revista -->
    <!ATTLIST contenido_revista enlace_revista CDATA #REQUIRED>
  
<!-- Definición de los atributos de periódicos-->
    <!ATTLIST periodicos id ID #REQUIRED>
    <!ELEMENT periodicos (periodico+)>
    
<!-- Definición de los atributos de periódico -->
    <!ATTLIST periodico id ID #REQUIRED>
    <!ATTLIST periodico tipo_clase (nacionales | internacionales ) #REQUIRED>
    <!ATTLIST periodico fecha_publicacion CDATA #REQUIRED>

<!ELEMENT periodico (titulo_periodico,indice_contenido,secciones_periodico)>
    <!ELEMENT titulo_periodico (#PCDATA)>
    <!ELEMENT indice_contenido (#PCDATA)>
    <!ELEMENT secciones_periodico (seccion*)>

<!-- Definición de los atributos de secciones -->
    <!ATTLIST secciones numero_paginas CDATA #REQUIRED>

<!-- Definición de los atributos de seccion -->
    <!ATTLIST seccion id (economica | opinion | deportes | nacional | internacional) #REQUIRED>

<!ELEMENT seccion (articulos)>
    <!ELEMENT articulos (contenido_articulos)>  
  
<!-- Definición de los atributos de articulos -->
    <!ATTLIST articulos autor CDATA #REQUIRED>

<!-- Definición de los atributos de contenido_articulos -->
    <!ATTLIST contenido_articulos enlace_periodico CDATA #REQUIRED>
 
 <!ELEMENT contenido_articulos (enlace_periodico*)>

=== beadeval/Actividad2/Actividad2/A2Requerimiento1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE biblioteca SYSTEM "A2Requerimiento1.dtd">

<biblioteca>
    <!--Libros-->
  <libros id="L">
    <!--Atributos de libros tipo novela-->
   <libro id="L0001" tipo_clase="novela" numero_paginas="Numero paginas">
          <titulo>Titulo de Novela </titulo>
          <capitulo numero_paginas="Numero paginas">
               <nombre_capitulo>Nombre del capitulo</nombre_capitulo>
               <contenido enlace="https://www.actividad2.com"/>
          </capitulo>
          <indice_libro>Contenido del indice</indice_libro>
          <sinopsis>Contenido de la sinopsis</sinopsis>
    </libro>
   <!--Atributos de libros tipo infantil-->
    <libro id="L0002" tipo_clase="infantil" numero_paginas="Numero paginas">
          <titulo>Titulo de Libro Infantil</titulo>
          <capitulo numero_paginas="Numero paginas">
               <nombre_capitulo>Nombre del capitulo</nombre_capitulo>
               <contenido enlace="https://www.actividad2.com"/>
          </capitulo>
          <indice_libro>Contenido del indice</indice_libro>
          <sinopsis>Contenido de la sinopsis</sinopsis>
  </libro>
    <!--Atributos de libros tipo didáctico-->
    <libro id="L0003" tipo_clase="didactico" numero_paginas="Numero paginas">
          <titulo>Titulo de Libro Didáctico</titulo>
          <capitulo numero_paginas="Numero paginas">
               <nombre_capitulo>Nombre del capitulo</nombre_capitulo>
               <contenido enlace="https://www.actividad2.com"/>
          </capitulo>
          <indice_libro>Contenido del indice</indice_libro>
          <sinopsis>Contenido de la sinopsis</sinopsis>
    </libro>
    </libros>
    <!--Revistas-->
  <revistas id="R">
    <!--Atributos de revistas tipo informática-->
    <revista id="R0001" tipo_clase="informatica" numero_paginas="Numero de Páginas">
          <titulo_revista>Titulo Revista Informática</titulo_revista>
          <numero_revista>Número de Revista</numero_revista>
          <indice_revista>Contenido del índice</indice_revista>
          <secciones_revista numero_paginas= "Numero de páginas">
               <contenido_revista enlace_revista="https://www.actividad2.com"/>
          </secciones_revista>
    </revista>
    <!--Atributos de revistas tipo corazón-->
    <revista id="R0002" tipo_clase="corazon" numero_paginas="Numero de Páginas">
          <titulo_revista>Titulo Revista Corazón</titulo_revista>
          <numero_revista>Número de Revista</numero_revista>
          <indice_revista>Contenido del índice</indice_revista>
          <secciones_revista numero_paginas="Numero de páginas">
               <contenido_revista enlace_revista="https://www.actividad2.com"/>
          </secciones_revista>
    </revista>
    <!--Atributos de revistas tipo coches-->
    <revista id="R0003" tipo_clase="coches" numero_paginas="Numero de Páginas">
          <titulo_revista>Titulo Revista Coches</titulo_revista>
          <numero_revista>Número de Revista</numero_revista>
          <indice_revista>Contenido del índice</indice_revista>
          <secciones_revista numero_paginas="Numero de Páginas">
               <contenido_revista enlace_revista="https://www.actividad2.com"/>
          </secciones_revista>
    </revista>
    <!--Atributos de revistas tipo investigación-->
    <revista id="R0004" tipo_clase="investigacion" numero_paginas="Numero de Páginas">
          <titulo_revista>Titulo Revista Investigación</titulo_revista>
          <numero_revista>Número de Revista</numero_revista>
          <indice_revista>Contenido del índice</indice_revista>
          <secciones_revista numero_paginas="Numero de Páginas">
               <contenido_revista enlace_revista="https://www.actividad2.com"/>
          </secciones_revista>
    </revista>
    <!--Atributos de revistas tipo otras-->
    <revista id="R0005" tipo_clase="otras" numero_paginas="Numero de Páginas">
          <titulo_revista>Titulo Revista Otras</titulo_revista>
          <numero_revista>Número de Revista</numero_revista>
          <indice_revista>Contenido del índice</indice_revista>
          <secciones_revista numero_paginas="Numero de Páginas">
               <contenido_revista enlace_revista="https://www.actividad2.com"/>
          </secciones_revista>
    </revista>
  </revistas>
    
    <!--Periódicos-->
  <periodicos id="P">
    <!--Atributos de periódicos tipo nacional-->
    <periodico id="P0001" tipo_clase="nacionales" fecha_publicacion="Fecha publicacion">
          <titulo_periodico>Titulo del periódico</titulo_periodico>
          <indice_contenido>Indice contenido</indice_contenido>
          <secciones_periodico>
            <seccion id="economica">
              <articulos autor="Autor">
                <contenido_articulos enlace_periodico="https://www.actividad2.com"/>
              </articulos>
          </seccion>

           <seccion id="opinion">
              <articulos autor="Autor">
                <contenido_articulos enlace_periodico="https://www.actividad2.com"/>
              </articulos>
           </seccion>

           <seccion id="deportes">
              <articulos autor="Autor">
                <contenido_articulos enlace_periodico="https://www.actividad2.com"/>
              </articulos>
           </seccion>

           <seccion id="nacional">
              <articulos autor="Autor">
                <contenido_articulos enlace_periodico="https://www.actividad2.com"/>
              </articulos>
           </seccion>

           <seccion id="internacional">
              <articulos autor="Autor">
                <contenido_articulos enlace_periodico="https://www.actividad2.com"/>
              </articulos>
           </seccion>
          </secciones_periodico>
    </periodico>

    <!--Atributos de periódicos tipo internacional-->
    <periodico id="P0002" tipo_clase="internacionales" fecha_publicacion="Fecha publicacion">
          <titulo_periodico>Titulo del periódico</titulo_periodico>
          <indice_contenido>Indice contenido</indice_contenido>
          <secciones_periodico>
            <seccion id="economica">
              <articulos autor="Autor">
                <contenido_articulos enlace_periodico="https://www.actividad2.com"/>
              </articulos>
          </seccion>

           <seccion id="opinion">
              <articulos autor="Autor">
                <contenido_articulos enlace_periodico="https://www.actividad2.com"/>
              </articulos>
           </seccion>

           <seccion id="deportes">
              <articulos autor="Autor">
                <contenido_articulos enlace_periodico="https://www.actividad2.com"/>
              </articulos>
           </seccion>

           <seccion id="nacional">
              <articulos autor="Autor">
                <contenido_articulos enlace_periodico="https://www.actividad2.com"/>
              </articulos>
           </seccion>

           <seccion id="internacional">
              <articulos autor="Autor">
                <contenido_articulos enlace_periodico="https://www.actividad2.com"/>
              </articulos>
           </seccion>
          </secciones_periodico>
    </periodico>
  </periodicos>
</biblioteca>
